### ISSUE TITLE
Opam install error

### ISSUE THREAD

**Issue by timothee-haudebourg** [Z3Prover/z3#1622]
I'm trying to install z3 ocaml binding via opam. It doesn't work. The problem comes from the `mk_util.py` script: 
```
#   File "/home/timothee/.opam/4.06.1/build/z3.4.6/scripts/mk_util.py", line 892, in is_clang_in_gpp_form
#     version_string = check_output([cc, '--version']).encode('utf-8').decode('utf-8')
# UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 26: ordinal not in range(128)
```

I beleive this problem has already been taken care of: https://github.com/Z3Prover/z3/pull/1462, but the opam repo is not up to date yet. In the meanwhile, is it possible to make opam use python 3 instead of python 2.7? As specified in the pull request conversation:

> It's fine with Python 3.x (which assumes all strings are unicode), but not with 2.x (which assumes ASCII I think).

But the z3 package in opam is still configured to use python 2.7...

**Comment by timothee-haudebourg** [comment]
Following this issue, i've been able to trick `mk_util.py` into ignoring the copyright symbol outputed by `g++ --version` just by creating a little bash script:
```
#!/bin/sh
if [ $1 = "--version" ]
then
	echo "gcc (GCC) 8.1.0"
else
	/usr/bin/g++ $@
fi
```
So now i'm able to pass the configuration phase. But it's still not working!
Now a have a compile error:
```
### stderr ###
# In file included from ../src/util/lp/permutation_matrix.hpp:21,
#                  from ../src/util/lp/permutation_matrix_instances.cpp:22:
# ../src/util/lp/permutation_matrix.h: in the function « unsigned int* lp::permutation_matrix<T, X>::values() const »:
# ../src/util/lp/permutation_matrix.h:135:44: error: cannot convert « const vector<unsigned int> » into « unsigned int* » in the return statement:
#          unsigned * values() const { return m_permutation; }
#                                             ^~~~~~~~~~~~~
# make: *** [Makefile:518: util/lp/permutation_matrix_instances.o] Error 1
```
(sorry if the error message is not exactly the correct, i had to translate it in english).

It seems to work with g++ 7.3.x however (we've tested on an other computer).

**Comment by timothee-haudebourg** [comment]
Ok, so I just have to wait for the opam package to be updated.

**Comment by maroneze** [comment]
I just encountered the `permutation_matrix` compilation error mentioned above when trying to install z3 4.6 (after a user of our package, which depends on z3, reported installing it, so I wanted to reproduce their configuration).

Just to clarify, is it due to the g++ version (I'm using gcc 9.1), and therefore impossible to blacklist it on opam-repository? Just checking so that I can inform our user whether they should upgrade their version of z3.

**Comment by Vancir** [comment]
I also encountered the same problem when compiling the latest code d2330055e732dacc9423f54a271fdaa235515ad0, but when I checkout to release 4.8.10, it could be compiled successfully.

Environment: Ubuntu 20.04.2 GCC (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
