### ISSUE TITLE
CMake build fails to link to librt for old glibc

### ISSUE THREAD

**Issue by jeremy-murphy** [Z3Prover/z3#1437]
I just tried using the CMake (3.6.1) build on CentOS 6.8 with devtoolset 2 (GCC 4.8.2) and hit this link error: 

> [100%] Linking CXX executable ../../z3
> /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: CMakeFiles/shell.dir/datalog_frontend.cpp.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
> /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: note: 'clock_gettime@@GLIBC_2.2.5' is defined in DSO /lib64/librt.so.1 so try adding it to the linker command line
> /lib64/librt.so.1: could not read symbols: Invalid operation
> collect2: error: ld returned 1 exit status
> make[2]: *** [z3] Error 1

Cheers.

**Comment by jeremy-murphy** [comment]
Btw, the standard build method works fine.

**Comment by delcypher** [comment]
@jeremy-murphy Thanks for reporting. We current test in CI GCC 4.8.2 however we don't test (and I have never tested) with a distro as old as CentOS 6.8.

IIUC the reason you see this error is that you're using a very old version of glibc. According to the `clock_gettime` man page it was only necessary to link with `librt` for glibc versions before 2.17.

The other build system explicitly passes `-lrt` to the compiler. We need to fix the CMake build system to link against this library when necessary.

**Comment by jeremy-murphy** [comment]
Hi. Yup, sounds right: CentOS 6.8 uses GLIBC 2.12.

**Comment by delcypher** [comment]
@jeremy-murphy Okay I've reproduced this locally. I'll try to write a fix tomorrow.

**Comment by delcypher** [comment]
@jeremy-murphy If you need a quick workaround you can apply this change locally to fix the build.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0be2de5..80198aa 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -234,6 +234,7 @@ if ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
   if ("${TARGET_ARCHITECTURE}" STREQUAL "x86_64")
     list(APPEND Z3_COMPONENT_CXX_DEFINES "-D_USE_THREAD_LOCAL")
   endif()
+  list(APPEND Z3_DEPENDENT_LIBS "rt")
 elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Darwin")
   # Does OSX really not need any special flags?
   message(STATUS "Platform: Darwin")
```
