### ISSUE TITLE
C++ api linking error due to missing inline in z3++.h

### ISSUE THREAD

**Issue by mttnff** [Z3Prover/z3#371]
Multiple includes of z3++.h lead to the following errors:
`multiple definition of z3::context::get_interpolant`
`multiple definition of z3::context::compute_interpolant`

Minimal example:
```
// ##### main.cpp #####
#include <z3++.h>
int main() {}
// ##### some.cpp ######
#include <z3++.h>
void someFunc() {}

$ g++/clang++ *.cpp
```

The problem seems to be a missing `inline` for these functions (introduced in 6580f1da).

**Comment by wintersteiger** [comment]
Thanks for the report! This is now fixed in master.
