### ISSUE TITLE
OCaml API fails to build on OCaml 4.06.1

### ISSUE THREAD

**Issue by sb98052** [Z3Prover/z3#1623]
When trying to build the OCaml API via mk_make.py, I get this:

ocamlc  -I api/ml -o api/ml/z3.cmi -c api/ml/z3.mli
File "api/ml/z3.mli", line 1159, characters 35-50:
Error: Unbound module Big_int
make: *** [api/ml/z3.cmo] Error 2

gwsapan-mbp:build gwsapan$ ocaml --version
The OCaml toplevel, version 4.06.1

The problem appears to be that Big_int is no longer distributed as part of the standard library, and the `num` library is not linked with.
